/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testPackage;

import boardviewer.BoardViewerPanelManager;
import drawpanel.DrawPanel;
import drawpanel.DrawableObject;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import mechanics.GameMechanics;
import mechanics.Hex;
import mechanics.JunctionEntity;
import mechanics.JunctionEntityClass;
import parser.GUIParser;
import parser.Game;
import parser.GameParser;
import serializer.SaverLoader;
import solver.CardWalker;
import solver.Solver;

/**
 *
 * @author Paweł
 */
public class TestFrame1 extends javax.swing.JFrame {
    BoardViewerPanelManager bvpm;
    GameMechanics mechanics;
    Game game;
    GameParser gameParser;
    GUIParser guiParser;
    parser.PlayerToServerParser p2sp;
    parser.OverParser overParser;

    DrawableObject chosenObject;

    int playerNumber = 0;
    int[] road = new int[2];
    int roadIterator = 0;

    /** Creates new form TestFrame1 */
    public TestFrame1() {
        initComponents();

        this.setLocationRelativeTo( null );
        this.playerInfoFrame.pack();
        this.playerInfoFrame.setLocationRelativeTo( rootPane );
        this.cardStackFrame.pack();
        this.cardStackFrame.setLocationRelativeTo( this );
        this.logFramer.pack();
        this.logFramer.setLocationRelativeTo( null );
        this.serialFrame.pack();
        this.serialFrame.setLocationRelativeTo( null );

        //wlasne
        this.mechanics = new GameMechanics( 4 );
        this.bvpm = new BoardViewerPanelManager( (DrawPanel) panel1, mechanics );
        this.bvpm.initBoardPanel();
        this.game = new Game( this.mechanics );
        this.gameParser = new GameParser( this.game );
        this.p2sp = new parser.PlayerToServerParser( game );
        this.overParser = new parser.OverParser( gameParser, guiParser, logBox, chatBox, null );
        this.overParser.setGameParser( gameParser );
        this.overParser.setP2sp( p2sp );
        this.overParser.setChatBox( chatBox );
        this.overParser.setLogBox( logBox );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerInfoFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        playerInfoArea = new javax.swing.JTextArea();
        cardStackFrame = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        cardStackArea = new javax.swing.JTextArea();
        jMenuItem2 = new javax.swing.JMenuItem();
        logFramer = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        logAreaText = new javax.swing.JTextArea();
        serialFrame = new javax.swing.JFrame();
        serialArea = new java.awt.TextArea();
        panel1 = new DrawPanel();
        reloadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        removeButton = new javax.swing.JButton();
        playerNumberLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        townButton = new javax.swing.JButton();
        cityButton = new javax.swing.JButton();
        thiefButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoRoadArea = new javax.swing.JTextArea();
        roadButton = new javax.swing.JButton();
        addRoadButton = new javax.swing.JButton();
        positionLabel = new javax.swing.JLabel();
        devCardButton = new javax.swing.JButton();
        resourceTextField = new javax.swing.JTextField();
        addResourceButton = new javax.swing.JButton();
        removeResourceButton = new javax.swing.JButton();
        rollButton = new javax.swing.JButton();
        commandField = new javax.swing.JTextField();
        commandSendButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chatBox = new java.awt.TextArea();
        jLabel3 = new javax.swing.JLabel();
        logBox = new java.awt.TextArea();
        overParserField = new javax.swing.JTextField();
        overParserButton = new javax.swing.JButton();
        playerInfoRealArea = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        logMenuButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        debugJunctions = new javax.swing.JMenuItem();
        saveMenu = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        playerInfoFrame.setTitle("playerInfo");

        playerInfoArea.setColumns(20);
        playerInfoArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        playerInfoArea.setRows(5);
        playerInfoArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerInfoAreaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(playerInfoArea);

        javax.swing.GroupLayout playerInfoFrameLayout = new javax.swing.GroupLayout(playerInfoFrame.getContentPane());
        playerInfoFrame.getContentPane().setLayout(playerInfoFrameLayout);
        playerInfoFrameLayout.setHorizontalGroup(
            playerInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        playerInfoFrameLayout.setVerticalGroup(
            playerInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardStackFrame.setTitle("cardStack");

        cardStackArea.setColumns(20);
        cardStackArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cardStackArea.setRows(5);
        cardStackArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardStackAreaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(cardStackArea);

        javax.swing.GroupLayout cardStackFrameLayout = new javax.swing.GroupLayout(cardStackFrame.getContentPane());
        cardStackFrame.getContentPane().setLayout(cardStackFrameLayout);
        cardStackFrameLayout.setHorizontalGroup(
            cardStackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStackFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardStackFrameLayout.setVerticalGroup(
            cardStackFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStackFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuItem2.setText("jMenuItem2");

        logFramer.setTitle("log box");

        logAreaText.setColumns(20);
        logAreaText.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        logAreaText.setRows(5);
        jScrollPane5.setViewportView(logAreaText);

        javax.swing.GroupLayout logFramerLayout = new javax.swing.GroupLayout(logFramer.getContentPane());
        logFramer.getContentPane().setLayout(logFramerLayout);
        logFramerLayout.setHorizontalGroup(
            logFramerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logFramerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        logFramerLayout.setVerticalGroup(
            logFramerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logFramerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        serialFrame.setTitle("save/load");

        serialArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serialAreaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout serialFrameLayout = new javax.swing.GroupLayout(serialFrame.getContentPane());
        serialFrame.getContentPane().setLayout(serialFrameLayout);
        serialFrameLayout.setHorizontalGroup(
            serialFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serialArea, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        serialFrameLayout.setVerticalGroup(
            serialFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serialArea, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("osadnicy testy");

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel1MouseMoved(evt);
            }
        });
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        reloadButton.setText("reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        infoArea.setColumns(20);
        infoArea.setRows(5);
        jScrollPane1.setViewportView(infoArea);

        removeButton.setText("remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        playerNumberLabel.setText("0");

        jLabel2.setText("Player");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        townButton.setText("Add town");
        townButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townButtonActionPerformed(evt);
            }
        });

        cityButton.setText("Add city");
        cityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityButtonActionPerformed(evt);
            }
        });

        thiefButton.setText("reverseThief");
        thiefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thiefButtonActionPerformed(evt);
            }
        });

        infoRoadArea.setColumns(20);
        infoRoadArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        infoRoadArea.setRows(5);
        infoRoadArea.setText("roadInfo");
        jScrollPane2.setViewportView(infoRoadArea);

        roadButton.setText("getRoad");
        roadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roadButtonActionPerformed(evt);
            }
        });

        addRoadButton.setText("addRoad");
        addRoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoadButtonActionPerformed(evt);
            }
        });

        positionLabel.setText("jLabel1");

        devCardButton.setText("devCardGet");
        devCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devCardButtonActionPerformed(evt);
            }
        });

        resourceTextField.setText("res");

        addResourceButton.setText("+");
        addResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResourceButtonActionPerformed(evt);
            }
        });

        removeResourceButton.setText("-");
        removeResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeResourceButtonActionPerformed(evt);
            }
        });

        rollButton.setText("roll");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        commandField.setText("command");

        commandSendButton.setText("d");
        commandSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandSendButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Czat");

        jLabel3.setText("Log");

        logBox.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        logBox.setMaximumSize(new java.awt.Dimension(60, 32767));
        logBox.setMinimumSize(new java.awt.Dimension(60, 80));
        logBox.setPreferredSize(new java.awt.Dimension(60, 80));

        overParserField.setText("overParserCommand");

        overParserButton.setText("jButton1");
        overParserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overParserButtonActionPerformed(evt);
            }
        });

        playerInfoRealArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        playerInfoRealArea.setMinimumSize(new java.awt.Dimension(60, 80));
        playerInfoRealArea.setPreferredSize(new java.awt.Dimension(60, 80));
        playerInfoRealArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerInfoRealAreaMouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("playerInfo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("cardStack");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        logMenuButton.setText("log");
        logMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMenuButtonActionPerformed(evt);
            }
        });
        jMenu1.add(logMenuButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        debugJunctions.setText("junction5");
        debugJunctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugJunctionsActionPerformed(evt);
            }
        });
        jMenu2.add(debugJunctions);

        saveMenu.setText("save");
        saveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuActionPerformed(evt);
            }
        });
        jMenu2.add(saveMenu);

        jMenuItem4.setText("load");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reloadButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playerNumberLabel))
                                    .addComponent(removeButton))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(townButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityButton)
                            .addComponent(thiefButton)
                            .addComponent(roadButton)
                            .addComponent(addRoadButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(devCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resourceTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addResourceButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rollButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(overParserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(commandSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overParserField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(commandField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeResourceButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(chatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(playerInfoRealArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reloadButton)
                                    .addComponent(playerNumberLabel)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(townButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cityButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thiefButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addRoadButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(devCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addResourceButton)
                            .addComponent(removeResourceButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logBox, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(chatBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerInfoRealArea, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overParserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(overParserButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollButton)
                            .addComponent(commandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commandSendButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        this.mechanics = new GameMechanics( 4 );
        this.bvpm = new BoardViewerPanelManager( (DrawPanel) panel1, mechanics );
        this.bvpm.initBoardPanel();
        this.bvpm.repaint();
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void panel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseMoved
        int x = evt.getX();
        int y = evt.getY();

        this.positionLabel.setText( x + ":" + y );

    }//GEN-LAST:event_panel1MouseMoved

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        String txt = "";
        int x = evt.getX();
        int y = evt.getY();
        this.chosenObject = this.bvpm.getDpm().getObjects( x, y )[0];
        txt += this.chosenObject.getId();
        this.infoArea.setText( txt );
    }//GEN-LAST:event_panel1MouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        this.bvpm.getDpm().removeObjectById( this.infoArea.getText() );
        this.bvpm.repaint();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.playerNumber++;
        if ( this.playerNumber > 3 ) {
            this.playerNumber = 0;
        }

        this.playerNumberLabel.setText( "" + this.playerNumber );
    }//GEN-LAST:event_jLabel2MouseClicked

    private void townButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townButtonActionPerformed
        String txt = this.infoArea.getText();
        txt = txt.substring( txt.lastIndexOf( "_" ) + 1 );
        if ( txt.charAt( 0 ) == '0' ) {
            txt = txt.substring( 1 );
        }
        int jNum = Integer.parseInt( txt );
        this.mechanics.setTownAtJunctionToPlayer( jNum, playerNumber );
        this.bvpm.reconsiderJunctions();
        this.bvpm.repaint();
    }//GEN-LAST:event_townButtonActionPerformed

    private void cityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityButtonActionPerformed
        String txt = this.infoArea.getText();
        txt = txt.substring( txt.lastIndexOf( "_" ) + 1 );
        if ( txt.charAt( 0 ) == '0' ) {
            txt = txt.substring( 1 );
        }
        int jNum = Integer.parseInt( txt );
        this.mechanics.setCityAtJunctionToPlayer( jNum, playerNumber );
        this.bvpm.reconsiderJunctions();
        this.bvpm.repaint();
    }//GEN-LAST:event_cityButtonActionPerformed

    private void thiefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thiefButtonActionPerformed
        String txt = this.infoArea.getText();
        txt = txt.substring( txt.lastIndexOf( "_" ) + 1 );
        if ( txt.charAt( 0 ) == '0' ) {
            txt = txt.substring( 1 );
        }
        int hNum = Integer.parseInt( txt );

        Hex hex = this.mechanics.getHexs()[hNum];
        boolean isEn = hex.isEnabled();
        hex.setEnabled( !isEn );
        //deb
        System.out.println( "hex" + hNum + " " + hex.isEnabled() );
        this.bvpm.reconsiderThief();
        this.bvpm.repaint();
    }//GEN-LAST:event_thiefButtonActionPerformed

    private void roadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roadButtonActionPerformed
        this.road[this.roadIterator] = Integer.parseInt( this.infoArea.getText().substring( this.infoArea.getText().lastIndexOf( "_" ) + 1 ) );
        this.roadIterator = (this.roadIterator + 1) % 2;
        this.infoRoadArea.setText( "" + this.road[0] + ":" + this.road[1] );
    }//GEN-LAST:event_roadButtonActionPerformed

    private void addRoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoadButtonActionPerformed
        //deb
        System.out.println( "poziom jframe, dodaje deroge road[0]=" + road[0] + ",road[1]=" + road[1] );
        this.mechanics.addRoadBetweenJunctionsToPlayer( road[0], road[1], playerNumber );
        this.bvpm.reconsiderRoads();
        this.bvpm.repaint();
    }//GEN-LAST:event_addRoadButtonActionPerformed

    private void playerInfoAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerInfoAreaMouseClicked
        if ( evt.getButton() == MouseEvent.BUTTON3 ) {
            String out = "";
            for ( int i = 0; i < this.mechanics.getPlayers().length; i++ ) {
                out += this.mechanics.getPlayers()[i].getInfo() + "\n";
            }
            this.playerInfoArea.setText( out );
        }
    }//GEN-LAST:event_playerInfoAreaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.playerInfoFrame.setVisible( true );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.cardStackFrame.setVisible( true );
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cardStackAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardStackAreaMouseClicked
        if ( evt.getButton() == MouseEvent.BUTTON3 ) {
            this.cardStackArea.setText( CardWalker.getCardsInfo( this.mechanics.getCardStack() ) );
        }
    }//GEN-LAST:event_cardStackAreaMouseClicked

    private void devCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devCardButtonActionPerformed
        this.mechanics.giveDevelopementCardToPlayer( this.playerNumber );
    }//GEN-LAST:event_devCardButtonActionPerformed

    private void addResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResourceButtonActionPerformed
        int[] res = Solver.getResourcesFromString( this.resourceTextField.getText() );
        this.mechanics.addResourcesToPlayer( res, playerNumber );
    }//GEN-LAST:event_addResourceButtonActionPerformed

    private void removeResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeResourceButtonActionPerformed
        int[] res = Solver.getResourcesFromString( this.resourceTextField.getText() );
        for ( int i = 0; i < res.length; i++ ) {
            res[i] = -res[i];
        }
        this.mechanics.addResourcesToPlayer( res, playerNumber );
    }//GEN-LAST:event_removeResourceButtonActionPerformed

    private void logMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMenuButtonActionPerformed
        this.logFramer.setVisible( true );
    }//GEN-LAST:event_logMenuButtonActionPerformed

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        String[] mes = this.game.roll();
        this.logAreaText.append( mes[0] + "\n" + mes[1] + "\n" );
        this.gameParser.parse( mes[0] );
    }//GEN-LAST:event_rollButtonActionPerformed

    private void debugJunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugJunctionsActionPerformed
        JunctionEntity jGlobal = this.mechanics.getJunctions()[5];
        JunctionEntity jHex = this.mechanics.getHexs()[1].getJunctions()[3];
        JunctionEntity jHex3 = this.mechanics.getHexs()[3].getJunctions()[0];

        if ( jGlobal.getEntityClass() != JunctionEntityClass.NONE ) {
            System.out.println( "global nie none" );
            System.out.println( jGlobal.getPlayerNumber() );
        } else {
            System.out.println( "global none" );
        }

        if ( jHex.getEntityClass() != JunctionEntityClass.NONE ) {
            System.out.println( "hex1 nie none" );
            System.out.println( jHex.getPlayerNumber() );
        } else {
            System.out.println( "hex1 none" );
        }

        if ( jHex3.getEntityClass() != JunctionEntityClass.NONE ) {
            System.out.println( "hex3 nie none" );
            System.out.println( jHex3.getPlayerNumber() );
        } else {
            System.out.println( "hex3 none" );
        }
    }//GEN-LAST:event_debugJunctionsActionPerformed

    private void commandSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandSendButtonActionPerformed
        this.gameParser.parse( this.commandField.getText() );
        this.bvpm.reconsiderJunctions();
        this.bvpm.reconsiderRoads();
        this.bvpm.reconsiderThief();
        this.bvpm.repaint();
    }//GEN-LAST:event_commandSendButtonActionPerformed

    private void overParserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overParserButtonActionPerformed
        this.overParser.parse( this.overParserField.getText() );
        this.bvpm.reconsiderJunctions();
        this.bvpm.reconsiderRoads();
        this.bvpm.reconsiderThief();
        this.bvpm.repaint();
    }//GEN-LAST:event_overParserButtonActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        this.serialFrame.setVisible( true );
        String omg = "brak";
        try {
            System.out.println( "serializuje" );
            omg = serializer.SaverLoader.save( mechanics );
            this.serialArea.setText( omg );
        } catch ( java.io.IOException e ) {
            JOptionPane.showMessageDialog( rootPane, e );
        }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void saveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuActionPerformed
        this.serialFrame.setVisible( true );
        String omg = "brak";
        try {
            System.out.println( "serializuje" );
            omg = serializer.SaverLoader.save( mechanics );
            this.serialArea.setText( omg );
        } catch ( java.io.IOException e ) {
            JOptionPane.showMessageDialog( rootPane, e );
        }
    }//GEN-LAST:event_saveMenuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.serialFrame.setVisible( true );
        this.serialArea.setText( "" );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void serialAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serialAreaMouseClicked
        if ( evt.getButton() == 3 ) {
            try {
                GameMechanics gm = SaverLoader.load( this.serialArea.getText() );
                this.serialFrame.setVisible( false );
                this.mechanics = gm;
                this.bvpm = new BoardViewerPanelManager( (DrawPanel) panel1, mechanics );
                this.bvpm.initBoardPanel();
                this.game = new Game( this.mechanics );
                this.gameParser = new GameParser( this.game );
                this.p2sp = new parser.PlayerToServerParser( game );
                this.overParser = new parser.OverParser( gameParser, guiParser, logBox, chatBox, null );
                this.overParser.setGameParser( gameParser );
                this.overParser.setP2sp( p2sp );
                this.overParser.setChatBox( chatBox );
                this.overParser.setLogBox( logBox );
                this.bvpm.reconsiderJunctions();
                this.bvpm.reconsiderRoads();
                this.bvpm.reconsiderThief();
                this.bvpm.repaint();
            } catch ( Exception e ) {
                JOptionPane.showMessageDialog( rootPane, e );
            }
        }
    }//GEN-LAST:event_serialAreaMouseClicked

    private void playerInfoRealAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerInfoRealAreaMouseClicked
        this.playerInfoRealArea.setText( Solver.player2InfoStringReal( mechanics, playerNumber ) );
    }//GEN-LAST:event_playerInfoRealAreaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Windows".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( TestFrame1.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( TestFrame1.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( TestFrame1.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( TestFrame1.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new TestFrame1().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResourceButton;
    private javax.swing.JButton addRoadButton;
    private javax.swing.JTextArea cardStackArea;
    private javax.swing.JFrame cardStackFrame;
    private java.awt.TextArea chatBox;
    private javax.swing.JButton cityButton;
    private javax.swing.JTextField commandField;
    private javax.swing.JButton commandSendButton;
    private javax.swing.JMenuItem debugJunctions;
    private javax.swing.JButton devCardButton;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JTextArea infoRoadArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea logAreaText;
    private java.awt.TextArea logBox;
    private javax.swing.JFrame logFramer;
    private javax.swing.JMenuItem logMenuButton;
    private javax.swing.JButton overParserButton;
    private javax.swing.JTextField overParserField;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextArea playerInfoArea;
    private javax.swing.JFrame playerInfoFrame;
    private java.awt.TextArea playerInfoRealArea;
    private javax.swing.JLabel playerNumberLabel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeResourceButton;
    private javax.swing.JTextField resourceTextField;
    private javax.swing.JButton roadButton;
    private javax.swing.JButton rollButton;
    private javax.swing.JMenuItem saveMenu;
    private java.awt.TextArea serialArea;
    private javax.swing.JFrame serialFrame;
    private javax.swing.JButton thiefButton;
    private javax.swing.JButton townButton;
    // End of variables declaration//GEN-END:variables
}
